### ISSUE TITLE
Chrome: 0 error/0 warning shown for a fraction of second

### ISSUE THREAD

**Issue by mgueury** [mgueury/html_validator#37]
Chrome only.
Go to www.google.com
Open Devtools
Open the HTML Validator tab
For some seconds, the 0 errors / 0 warnings will be shown.
-> expected behavior: nothing or something like "Validation in progress..."

**Comment by mgueury** [comment]
tidy_lib.js:134 abort(7) at Error
    at jsStackTrace (chrome-extension://dnkembmimjacgkcdjldfmbcmgffgmlhg/common/tidy_emscripten.js:1076:13)
    at stackTrace (chrome-extension://dnkembmimjacgkcdjldfmbcmgffgmlhg/common/tidy_emscripten.js:1093:22)
    at abort (chrome-extension://dnkembmimjacgkcdjldfmbcmgffgmlhg/common/tidy_emscripten.js:57734:44)
    at b7 (chrome-extension://dnkembmimjacgkcdjldfmbcmgffgmlhg/common/tidy_emscripten.js:57361:2)
    at _tidyCreate (chrome-extension://dnkembmimjacgkcdjldfmbcmgffgmlhg/common/tidy_emscripten.js:55648:58)
    at _main (chrome-extension://dnkembmimjacgkcdjldfmbcmgffgmlhg/common/tidy_emscripten.js:10392:7)
at Object.callMain (chrome-extension://dnkembmimjacgkcdjldfmbcmgffgmlhg/common/tidy_emscripten.js:57618:30)
at TidyLib.getErrorsInHTML (chrome-extension://dnkembmimjacgkcdjldfmbcmgffgmlhg/common/tidy_lib.js:129:14)
at TidyResult.tidy_Filter (chrome-extension://dnkembmimjacgkcdjldfmbcmgffgmlhg/common/tidy_util.js:1401:20)
at TidyResult.validate_with_algorithm (chrome-extension://dnkembmimjacgkcdjldfmbcmgffgmlhg/common/tidy_util.js:1341:14)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by mgueury** [comment]
Fixed in 0.985 - tidyViewSource.js. Check if the emscripten module is loaded before to validate the html.
